# configure_file.pri - qmake implementation of CMake's configure_file function
# Usage: configure_file(input_file, output_file)

_NEWLINE = $$escape_expand("\\n")

# A function that mimics the logic of @VAR@ cmake macro
defineReplace(replaceAtSignVars) {
    line = $$1
    #message("replaceAtSignVars line: $$line")
    # 1. Split a string into a list based on the ‘@’ character
    # The text will be split into even and odd elements.
    # Elements that were BETWEEN ‘@’ characters will become every other element in the list.
    parts = $$split(line, "@")

    # A temporary variable for constructing the final string
    result_line = ""
    is_variable = false

    # 2. We iterate through all parts of the string
    for(part, parts) {
        #message("replaceAtSignVars part: $$part")
        # Since the first element always comes BEFORE the first ‘@’,
        # the is_variable flag is initially false and then alternates.

        equals(is_variable, true) {
            # Check if there is a qmake variable with that name
            defined($$part, var) {
                # Retrieve the value of a variable using $$eval()
                actual_value = $$eval($$part)
                result_line = "$$result_line$$actual_value"
            } else {
                # If the variable is not found in qmake, return it as text with @
                # (Or you can remove it or leave it empty, following CMake's logic)
                result_line = "$$result_line@$$part@"
            }
            is_variable = false
        } else {
            # This is a simple text (behind @-symbol)
            result_line = "$$result_line$$part"
            is_variable = true
        }
    }
    #message("result_line: $$result_line")
    return($$result_line)
}

# A function that mimics the logic of #cmakedefine for a single line
defineReplace(process_cmakedefine) {
    line = $$1

    # 1. Check whether a string contains the “#cmakedefine” macro
    # The regular expression searches for the word #cmakedefine followed by a variable name
    # The pattern “^.*?#cmakedefine\\s+([^\\s]+).*$” matches the variable name    contains(line, ".*$${LITERAL_HASH}cmakedefine.*") {
    contains(line, ".*$${LITERAL_HASH}cmakedefine.*") {
        # Extract the variable name (everything that comes immediately after #cmakedefine)
        VAR_NAME = $$replace(line, "^.*cmakedefine\\s+([^\\s;\\n\r]+).*$", "\\1")
        #message("$${LITERAL_HASH}cmakedefine spotted. Varname: $$VAR_NAME")

        # Check whether this variable is defined in qmake and whether it is non-empty
        # (In qmake, an invalid value is an empty variable, for example: MY_VAR = )
        defined($$VAR_NAME, var) {
            #message("$$VAR_NAME defined")
            VAR_VALUE = $$eval($$VAR_NAME)

            # If a variable is defined but explicitly set to “OFF” or “FALSE” (CMake style)
            # then we consider it to be disabled
            equals(VAR_VALUE, "OFF")|equals(VAR_VALUE, "FALSE")|equals(VAR_VALUE, "0") {
                IS_ENABLED = false
            } else {
                IS_ENABLED = true
            }
        } else {
            #message("$$VAR_NAME undefined")
            IS_ENABLED = false
        }

        # 2. Construct the output string based on the variable's status
        equals(IS_ENABLED, true) {
            # If the variable has a value, we substitute it (as in CMake)
            !isEmpty(VAR_VALUE)|equals(VAR_VALUE, "ON")|equals(VAR_VALUE, "TRUE") {
                # If the value is simply a flag like ON/TRUE, CMake usually writes #define VAR
                # If there is specific text or a number, it writes #define VAR value
                equals(VAR_VALUE, "ON")|equals(VAR_VALUE, "TRUE") {
                    NEW_line = "$${LITERAL_HASH}define $$VAR_NAME"
                } else {
                    NEW_line = "$${LITERAL_HASH}define $$VAR_NAME $$VAR_VALUE"
                }
            } else {
                NEW_line = "$${LITERAL_HASH}define $$VAR_NAME"
            }
        } else {
            # If a variable is disabled or does not exist, comment it out according to the CMake standard
            NEW_line = "/* $${LITERAL_HASH}undef $$VAR_NAME */"
        }
        #message("Returned new value: $$NEW_line")
        return($$NEW_line)
    }

    # If the string does not contain #cmakedefine, we return it unchanged
    return($$line)
}

defineTest(configure_file) {
    input_file = $$1
    output_file = $$2

    #message("configure_file(input=$$input_file, output=$$output_file")

    # Read the input file
    lines = $$cat($$input_file, lines)

    #message("Contents of $$input_file:$$_NEWLINE$$contents")

    # Start to write output file
    header = "// Generated by qmake. Do not edit!!!"
    win32{
        system(echo $$header > $$output_file)
    } else {
        system(echo \"$$header\" > \"$$output_file\")
    }
    for(line, lines) {
        #message("line: $$line")

        # Process @VAR@ variables
        pline = $$replaceAtSignVars($$line)

        # Process ${VAR} variables
        #while(true) {
        #    start_index = $$index($$line, "${")
        #    if(start_index < 0): break
        #    end_index = $$index($$line, "}", start_index+2)
        #    if(end_index < 0): break   # no closing }
        #    var = $$substring($$line, start_index+2, end_index-start_index-2)
        #    val = $$(var)
        #    if(isEmpty(val)) {
        #        warning("Variable $$var not found, replacing with empty string")
        #    }
        #    line = $$substring($$line, 0, start_index) + val + $$substring($$line, end_index+1)
        #}

        # Process #cmakedefine
        pline = $$process_cmakedefine($$pline)
        #message($$pline)
        # Append data to the output file
        win32{
            system(echo $$pline >> $$output_file)
        } else {
            system(echo \"$$pline\" >> \"$$output_file\")
        }
        #write_file($$output_file, pline, append)
    }

    return(true)
}
