# configure_file.pri - qmake implementation of CMake's configure_file function
# Usage: configure_file(input_file, output_file)

_NEWLINE = $$escape_expand("\\n")

defineReplace(replaceAtSignVars) {
    line = $$1
    message("replaceAtSignVars line: $$line")
    # 2. Розбиваємо рядок у список за символом '@'
    # Текст розділиться на парні та непарні елементи.
    # Елементи, які були МІЖ '@', стануть кожним другим елементом списку.
    parts = $$split(line, "@")

    # Тимчасова змінна для збирання фінального рядка
    result_line = ""
    is_variable = false

    # 3. Проходимо циклом по всіх частинах рядка
    for(part, parts) {
        message("replaceAtSignVars part: $$part")
        # Оскільки перший елемент завжди йде ДО першого '@',
        # прапорець is_variable спочатку false, а потім чергується.

        equals(is_variable, true) {
            # Перевіряємо, чи існує qmake-змінна з таким іменем
            defined($$part, var) {
                # Отримуємо значення змінної через $$eval()
                actual_value = $$eval($$part)
                result_line = "$$result_line$$actual_value"
            } else {
                # Якщо змінна не знайдена в qmake, повертаємо її як текст назад з @
                # (Або можете видалити/залишити порожньою за логікою CMake)
                result_line = "$$result_line@$$part@"
            }
            is_variable = false
        } else {
            # Це звичайний текст (поза символами @)
            result_line = "$$result_line$$part"
            is_variable = true
        }
    }
    message("result_line: $$result_line")
    return($$result_line)
}

defineTest(configure_file) {
    input_file = $$1
    output_file = $$2

    message("configure_file(input=$$input_file, output=$$output_file")
    message("VERSION: $$VERSION")
    message("PROJECT_VERSION_MAJOR: $$PROJECT_VERSION_MAJOR")
    message("PROJECT_VERSION_MINOR: $$PROJECT_VERSION_MINOR")
    message("PROJECT_VERSION_PATCH: $$PROJECT_VERSION_PATCH")

    # Read the input file
    win32 {
        #contents = $$system(type "$$input_file")
        lines = $$cat($$input_file, lines)
    } else {
        #contents = $$system(cat "$$input_file")
    }

    #message("Contents of $$input_file:$$_NEWLINE$$contents")

    # Split into lines
    #lines = $$split(contents, $${_NEWLINE})
    processed_lines = ""
    system(echo "// Generated by qmake" > "$$output_file")
    for(line, lines) {
        message("line: $$line")
        pline = $$replaceAtSignVars($$line)
        processed_lines += $$pline
        win32 {
            system((echo $$pline) >> "$$output_file")
        } else {
            system((printf '%s' $$pline) > "$$output_file")
        }

        # Process @VAR@ variables
        #start_index = $$section(line, "@", 0)
        #message("@-index: $$start_index")

        #while(true) {
        #    start_index = $$index($$line, "@")
        #    message("@-index: $$start_index")
        #    if(start_index < 0) {
        #        break
        #    }
        #    end_index = $$index($$line, "@", start_index+1)
        #    if(end_index < 0): break   # no closing @
        #    var = $$substring($$line, start_index+1, end_index-start_index-1)
        #    val = $$(var)
        #    if(isEmpty(val)) {
        #        warning("Variable $$var not found, replacing with empty string")
        #    }
        #    line = $$substring($$line, 0, start_index) + val + $$substring($$line, end_index+1)
        #}

        ## Process ${VAR} variables
        #while(true) {
        #    start_index = $$index($$line, "${")
        #    if(start_index < 0): break
        #    end_index = $$index($$line, "}", start_index+2)
        #    if(end_index < 0): break   # no closing }
        #    var = $$substring($$line, start_index+2, end_index-start_index-2)
        #    val = $$(var)
        #    if(isEmpty(val)) {
        #        warning("Variable $$var not found, replacing with empty string")
        #    }
        #    line = $$substring($$line, 0, start_index) + val + $$substring($$line, end_index+1)
        #}

        ## Process #cmakedefine
        #trimmed = $$line
        ## Remove leading spaces and tabs
        #while(!isEmpty(trimmed) && ($$equals($$left(trimmed, 1), " ") || $$equals($$left(trimmed, 1), "\\t"))) {
        #    trimmed = $$substring(trimmed, 1)
        #}
        #if($$starts_with(trimmed, "$${LITERAL_HASH}cmakedefine")) {
        #    rest = $$substring(trimmed, 12)   # after "#cmakedefine"
        #    # Remove leading spaces and tabs
        #    while(!isEmpty(rest) && ($$equals($$left(rest, 1), " ") || $$equals($$left(rest, 1), "\\t"))) {
        #        rest = $$substring(rest, 1)
        #    }
        #    # Split into variable and optional value
        #    parts = $$split(rest, " ")
        #    var = $$take_first(parts)
        #    val = $$join(parts, " ")   # value (may be empty)

        #    # Check variable value
        #    var_val = $$(var)
        #    if(!isEmpty(var_val) && !$$equals(var_val, "0")) {
        #        # True: define it
        #        if(isEmpty(val)) {
        #            new_line = "#define " + var
        #        } else {
        #            new_line = "#define " + var + " " + val
        #        }
        #    } else {
        #        # False: undef
        #        new_line = "/* #undef " + var + " */"
        #    }
        #    # Reconstruct line with original leading whitespace
        #    line = $$left($$line, $$index($$line, trimmed)) + new_line
        #}
        #processed_lines += $$line
    }

    # Join lines and write output file
    #output = $$join(processed_lines, "\\n")
    #win32 {
    #    system((echo $$output) > "$$output_file")
    #} else {
    #    system((printf '%s' $$output) > "$$output_file")
    #}
    #write_file($$output_file, "abc def")
    # 1. Створюємо список рядків (елементи будуть записані з нового рядка)
    MY_CONTENT =
    MY_CONTENT += "Line 1: Hello World"
    MY_CONTENT += "Line 2: Qmake is alive"

    # 2. Визначаємо шлях
    OUTPUT_PATH = $$OUT_PWD/output.txt

    # 3. Виклик функції. Вона ЗАВЖДИ повністю перезаписує файл.
    # Синтаксис: write_file(шлях_до_файлу, назва_змінної)
    #output = $$join(processed_lines, $${_NEWLINE})
    #output = "TEST"
    #message("OUPUT: $$output")
    #export(output)
    #write_file("$$output_file", output);
    #write_file($$OUT_PWD/defines.txt, DEFINES)
    #win32 {
    #    system((echo $$output) > "$$output_file")
    #    #system("cmd /c \"echo \"$$output\" > \"$$output_file\"\"")
    #} else {
    #    system((printf '%s' $$output) > "$$output_file")
    #}
    return(true)
}
