#ifndef MODBUS_CONFIG_H
#define MODBUS_CONFIG_H

#define MODBUSLIB_VERSION_MAJOR 0
#define MODBUSLIB_VERSION_MINOR 4
#define MODBUSLIB_VERSION_PATCH 0

#define MB_DYNAMIC_LINKING

/* #undef MBFFFF_READ_COILS_DISABLE */

#define MBF_READ_COILS_DISABLE                   
/* #undef MBF_READ_DISCRETE_INPUTS_DISABLE */
/* #undef MBF_READ_HOLDING_REGISTERS_DISABLE */
/* #undef MBF_READ_INPUT_REGISTERS_DISABLE */
/* #undef MBF_WRITE_SINGLE_COIL_DISABLE */
/* #undef MBF_WRITE_SINGLE_REGISTER_DISABLE */
/* #undef MBF_READ_EXCEPTION_STATUS_DISABLE */
#define MBF_DIAGNOSTICS_DISABLE                  
/* #undef MBF_GET_COMM_EVENT_COUNTER_DISABLE */
/* #undef MBF_GET_COMM_EVENT_LOG_DISABLE */
/* #undef MBF_WRITE_MULTIPLE_COILS_DISABLE */
/* #undef MBF_WRITE_MULTIPLE_REGISTERS_DISABLE */
/* #undef MBF_REPORT_SERVER_ID_DISABLE */
/* #undef MBF_READ_FILE_RECORD_DISABLE */
/* #undef MBF_WRITE_FILE_RECORD */
/* #undef MBF_MASK_WRITE_REGISTER_DISABLE */
/* #undef MBF_READ_WRITE_MULTIPLE_REGISTERS_DISABLE */
/* #undef MBF_READ_FIFO_QUEUE_DISABLE */


#endif // MODBUS_CONFIG_H
