#ifndef MODBUS_CONFIG_H
#define MODBUS_CONFIG_H

#define MODBUSLIB_VERSION_MAJOR 0
#define MODBUSLIB_VERSION_MINOR 5
#define MODBUSLIB_VERSION_PATCH 0

#define MB_DYNAMIC_LINKING

/* #undef MB_CLIENT_DISABLE */
/* #undef MB_SERVER_DISABLE */
/* #undef MB_C_SUPPORT_DISABLE */

/* #undef MBF_READ_COILS_DISABLE */
/* #undef MBF_READ_DISCRETE_INPUTS_DISABLE */
/* #undef MBF_READ_HOLDING_REGISTERS_DISABLE */
/* #undef MBF_READ_INPUT_REGISTERS_DISABLE */
/* #undef MBF_WRITE_SINGLE_COIL_DISABLE */
/* #undef MBF_WRITE_SINGLE_REGISTER_DISABLE */
/* #undef MBF_READ_EXCEPTION_STATUS_DISABLE */
/* #undef MBF_DIAGNOSTICS_DISABLE */
/* #undef MBF_GET_COMM_EVENT_COUNTER_DISABLE */
/* #undef MBF_GET_COMM_EVENT_LOG_DISABLE */
/* #undef MBF_WRITE_MULTIPLE_COILS_DISABLE */
/* #undef MBF_WRITE_MULTIPLE_REGISTERS_DISABLE */
/* #undef MBF_REPORT_SERVER_ID_DISABLE */
/* #undef MBF_READ_FILE_RECORD_DISABLE */
/* #undef MBF_WRITE_FILE_RECORD */
/* #undef MBF_MASK_WRITE_REGISTER_DISABLE */
/* #undef MBF_READ_WRITE_MULTIPLE_REGISTERS_DISABLE */
/* #undef MBF_READ_FIFO_QUEUE_DISABLE */
/* #undef MBF_ENCAPSULATED_INTERFACE_TRANSPORT_DISABLE */

/* #undef MBF_DIAGNOSTICS_RETURN_QUERY_DATA_DISABLE */
/* #undef MBF_DIAGNOSTICS_RESTART_COMMUNICATIONS_OPTION_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_DIAGNOSTIC_REGISTER_DISABLE */
/* #undef MBF_DIAGNOSTICS_CHANGE_ASCII_INPUT_DELIMITER_DISABLE */
/* #undef MBF_DIAGNOSTICS_FORCE_LISTEN_ONLY_MODE_DISABLE */
/* #undef MBF_DIAGNOSTICS_CLEAR_COUNTERS_AND_DIAGNOSTIC_REGISTER_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_BUS_MESSAGE_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_BUS_COMMUNICATION_ERROR_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_BUS_EXCEPTION_ERROR_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_SERVER_MESSAGE_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_SERVER_NO_RESPONSE_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_SERVER_NAK_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_SERVER_BUSY_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_RETURN_BUS_CHARACTER_OVERRUN_COUNT_DISABLE */
/* #undef MBF_DIAGNOSTICS_CLEAR_OVERRUN_COUNTER_AND_FLAG_DISABLE */

/* #undef MBF_MEI_READ_DEVICE_IDENTIFICATION_DISABLE */

/* #undef MB_ADDRESS_CLASS_DISABLE */

#endif // MODBUS_CONFIG_H
