CONFIG += skip_target_version_ext

PROJECT_VERSION_MAJOR = 0
PROJECT_VERSION_MINOR = 5
PROJECT_VERSION_PATCH = 2

VERSION = "$$PROJECT_VERSION_MAJOR.$$PROJECT_VERSION_MINOR.$$PROJECT_VERSION_PATCH.0"

