CONFIG += skip_target_version_ext

PROJECT_VERSION_MAJOR = 0
PROJECT_VERSION_MINOR = 4
PROJECT_VERSION_PATCH = 10

VERSION = "$${PROJECT_VERSION_MAJOR}.$${PROJECT_VERSION_MINOR}.$${PROJECT_VERSION_PATCH}.0"

message("VERSION: $$VERSION")

